# Generated by Django 4.2.6 on 2023-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('product_category', models.CharField(choices=[('Appliances', 'Appliances'), ('Furniture', 'Furniture'), ('Refrigerators', 'Refrigerators'), ('Smartphones', 'Smartphones'), ('Electronics', 'Electronics')], max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
